### ISSUE TITLE
Two quick questions

### ISSUE THREAD

**Issue by lfilho** [grvcoelho/vim-javascript-snippets#2]
Hey, @grvcoelho, nice work!
Two quick questions:
1. What is your build doing? There seems to be no real tests but you have a .travis.yml in place but it seems to be doing nothing...
2. Why not create contribute to https://github.com/honza/vim-snippets/tree/master/snippets/javascript instead of a new repo / dependency?

Thanks again for you work

**Comment by grvcoelho** [comment]
Hey :smile:!

1) The build is doing nothing, currently, but I intend to do some indentation check asap. Although, I use .editorconfig, an indentation check will prevent any inconsistencies made by contributions.

2) Although I really like honza's vim snippets (and use some of them in my workflow), I decided to create my own set of snippets with the triggers and snippets I want and with my personal preference. Take the `for` snippet for instance in which I use ES2015 `let` instead of a `var`. This project is intended to be just an archive of my own snippets, but it also happens to be useful for some people.

Regards!

**Comment by grvcoelho** [comment]
This issue also remembered be to give some credits to honza :smile:
